### ISSUE TITLE
Feature Request: Configure component files to build

### ISSUE THREAD

**Issue by trainiac** [ElementUI/element-theme#11]
Thanks! This is already working really well.

I'm using components of the entire element-ui library so I don't need to generate a css file for every single component.  Just base.css and the components that I'm using. It would cool if there was a way you could tell the cli to only build theme files that are necessary.

```
"components": [
  "button",
  "select",
  "option"
]
```

If you are open to the idea I can submit a PR.

**Comment by QingWei-Li** [comment]
Good idea. PR is welcome.

**Comment by trainiac** [comment]
Great! I'll take a look soon.  Looks like this line is where I will have most of the work. https://github.com/ElementUI/element-theme/blob/master/lib/task.js#L33

**Comment by QingWei-Li** [comment]
`0.7.0` is released.
