### ISSUE TITLE
无法初始化变量文件

### ISSUE THREAD

**Issue by suzi404** [ElementUI/element-theme#16]
![image](https://cloud.githubusercontent.com/assets/16069823/23397139/21b24d94-fdd2-11e6-80bf-ef0eb4de2d51.png)
按照官网提示，一步步走到这步，就报错
![image](https://cloud.githubusercontent.com/assets/16069823/23397160/3dafa7c6-fdd2-11e6-9223-6149c9bb112e.png)

**Comment by QingWei-Li** [comment]
没让你进 `node_modules/bin/` 是让你直接调用 `node_modules/bin/et`

**Comment by suzi404** [comment]
![image](https://cloud.githubusercontent.com/assets/16069823/23400967/daf7d8a6-fde0-11e6-89b2-38aea887f587.png)
我的是win，用的是命令行工具cmder

**Comment by QingWei-Li** [comment]
那就应该是反斜杠，不熟悉 npm 的机制的话你还是装全局吧
