### ISSUE TITLE
can not output file to the specified path

### ISSUE THREAD

**Issue by yeyuqiudeng** [ElementUI/element-theme#2]
![image](https://cloud.githubusercontent.com/assets/10278227/20034890/89f96b7a-a40a-11e6-805f-81b903127e33.png)

I have installed the `element-variables.css` to the specified path, but when I generated the theme, it aways alert `Not found variables file, please run "et -i"`

**Comment by yeyuqiudeng** [comment]
oh sorry, i forgot use `-c` before `-i`

**Comment by QingWei-Li** [comment]
fixed in `0.2.0`
