### ISSUE TITLE
按官网手册，在项目中安装et，在node_modules/.bin下执行 et -i 路径问题。

### ISSUE THREAD

**Issue by tangdw** [ElementUI/element-theme#3]
手册地址：[http://element.eleme.io/#/zh-CN/component/custom-theme](url)
我执行：
`F:\my-work\backstage-admin\node_modules\.bin>et -i`
`× Pleace install `element-theme-default``
最后我修改了一下路径
修改的js文件：
 `F:\my-work\backstage-admin\node_modules\element-theme\lib\config.js`
修改的代码：
`exports.themePath = path.resolve(process.cwd(), '../../node_modules/element-theme-default')`
（原谅我不知道怎么在这里贴图）

**Comment by QingWei-Li** [comment]
是让你执行 `node_modules\.bin\et -i` 不是让你到 `.bin` 目录下执行

**Comment by tangdw** [comment]
呃，不好意思

**Comment by tangdw** [comment]
呃，不好意思
