### ISSUE TITLE
Crashed with npm v3.10.9

### ISSUE THREAD

**Issue by luxp** [ElementUI/element-theme#4]
When I try to make my own theme, it throws error below, can you help me solve this issue?
Thanks.
```
$ node -v
v6.9.1

$ npm -v
3.10.9

$ et --version
0.2.0

$ et -i

√ Generator variables file

$ et

√ build theme font
- build element theme

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '\node_modules\element-theme-default\src\vue-popup\lib\popup.css'
    at Error (native)
```

**Comment by stefanosandes** [comment]
Same here!

**Comment by chanand** [comment]
Have a look at the workaround described at [theme-default](https://github.com/ElementUI/theme-default/issues/6#issuecomment-263486452)

**Comment by QingWei-Li** [comment]
fixed in https://github.com/QingWei-Li/postcss-salad/commit/0d062fe777f78cd7e4618980b7b103d69991f49f
