### ISSUE TITLE
et -i , please install `element-theme-chalk`

### ISSUE THREAD

**Issue by ninuxGithub** [ElementUI/element-theme#42]
根据readme提示，安装了
![image](https://user-images.githubusercontent.com/22161407/32536064-995f2da8-c497-11e7-85c1-1ef97a05a2c7.png)

但是在.bin目录：et -i 报错：please install `element-theme-chalk`
但是在element-theme-chalk/element-theme-chalk是安装成功的
为何？

**Comment by ninuxGithub** [comment]
fllow the step to install element-theme ,but when use the command "et -i" , it stills tell me that "element-theme-chalk" is no installed , actually element-theme-chalk has installed sucessfully, why?

**Comment by yinxianwei** [comment]
npm i element-theme -g

**Comment by ghost** [comment]
After lookuping the code, [calculate `themePath` by process.cwd()](https://github.com/ElementUI/element-theme/blob/6b2a112c6ba47893e7a4b6fb736fbe5d073b0dd5/lib/config.js#L17). Namely, you run `et -i`  on 
wrong path. You ought to run `et -i` on project root directory(not under .bin directory)

**Comment by ninuxGithub** [comment]
thanks very much , problem fixed
