### ISSUE TITLE
我就不懂了，改个主题颜色弄这么复杂干什么

### ISSUE THREAD

**Issue by bydff** [ElementUI/element-theme#75]
我就想改个primary的主题色，你看看又要下scss，又要编译那一堆东西，能不能搞个人性化的配置，看看隔壁，在vueconfig改个值就能改配置颜色，你这么繁琐不是劝退么，大部分人都不需要改那么多的。希望能搞个简单的操作来。

**Comment by busyrat** [comment]
不看文档的吗？

**Comment by 625781186** [comment]
哈哈 , 团队太懒 .
